version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: 'ci'

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: 'deps'

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: 'deps'
